version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=aqualog
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/aqualog?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/scripts/start.sh"]
    command: ["/app/server"]
