// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

type Value struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	ValueTypeID int32     `json:"value_type_id"`
	Value       float64   `json:"value"`
	CreatedAt   time.Time `json:"created_at"`
}

type ValueType struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Unit        string          `json:"unit"`
	UserID      int64           `json:"user_id"`
	Target      sql.NullFloat64 `json:"target"`
	Min         sql.NullFloat64 `json:"min"`
	Max         sql.NullFloat64 `json:"max"`
	CreatedAt   time.Time       `json:"created_at"`
}
