// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Param struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	ParamTypeID int64     `json:"param_type_id"`
	Value       float64   `json:"value"`
	Timestamp   time.Time `json:"timestamp"`
	CreatedAt   time.Time `json:"created_at"`
}

type ParamOrigin struct {
	ID            int64     `json:"id"`
	ParamTypeName string    `json:"param_type_name"`
	Name          string    `json:"name"`
	CreatedBy     string    `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
}

type ParamType struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Unit        string          `json:"unit"`
	UserID      int64           `json:"user_id"`
	Target      sql.NullFloat64 `json:"target"`
	Min         sql.NullFloat64 `json:"min"`
	Max         sql.NullFloat64 `json:"max"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	Admin          bool      `json:"admin"`
	CreatedAt      time.Time `json:"created_at"`
}
