// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: param_type.sql

package db

import (
	"context"
	"database/sql"
)

const createParamType = `-- name: CreateParamType :one
INSERT INTO param_types (
  name,
  description,
  unit,
  user_id,
  target,
  min,
  max
) VALUES (
  $1, 
  $2, 
  $3,
  $4,
  $5,
  $6,
  $7
) 
RETURNING id, name, description, unit, user_id, target, min, max, created_at
`

type CreateParamTypeParams struct {
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Unit        string          `json:"unit"`
	UserID      int64           `json:"user_id"`
	Target      sql.NullFloat64 `json:"target"`
	Min         sql.NullFloat64 `json:"min"`
	Max         sql.NullFloat64 `json:"max"`
}

func (q *Queries) CreateParamType(ctx context.Context, arg CreateParamTypeParams) (ParamType, error) {
	row := q.db.QueryRowContext(ctx, createParamType,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.UserID,
		arg.Target,
		arg.Min,
		arg.Max,
	)
	var i ParamType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UserID,
		&i.Target,
		&i.Min,
		&i.Max,
		&i.CreatedAt,
	)
	return i, err
}

const getParamType = `-- name: GetParamType :one
SELECT id, name, description, unit, user_id, target, min, max, created_at FROM param_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetParamType(ctx context.Context, id int64) (ParamType, error) {
	row := q.db.QueryRowContext(ctx, getParamType, id)
	var i ParamType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UserID,
		&i.Target,
		&i.Min,
		&i.Max,
		&i.CreatedAt,
	)
	return i, err
}

const getParamTypeByName = `-- name: GetParamTypeByName :one
SELECT id, name, description, unit, user_id, target, min, max, created_at FROM param_types
WHERE user_id = $1 AND name = $2
LIMIT 1
`

type GetParamTypeByNameParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetParamTypeByName(ctx context.Context, arg GetParamTypeByNameParams) (ParamType, error) {
	row := q.db.QueryRowContext(ctx, getParamTypeByName, arg.UserID, arg.Name)
	var i ParamType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UserID,
		&i.Target,
		&i.Min,
		&i.Max,
		&i.CreatedAt,
	)
	return i, err
}
