// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: param.sql

package db

import (
	"context"
	"time"
)

const createParam = `-- name: CreateParam :one
INSERT INTO params (
  user_id,
  param_type_id,
  value,
  timestamp
) VALUES (
  $1,
  $2,
  $3,
  $4
) 
RETURNING id, user_id, param_type_id, value, timestamp, created_at
`

type CreateParamParams struct {
	UserID      int64     `json:"user_id"`
	ParamTypeID int64     `json:"param_type_id"`
	Value       float64   `json:"value"`
	Timestamp   time.Time `json:"timestamp"`
}

func (q *Queries) CreateParam(ctx context.Context, arg CreateParamParams) (Param, error) {
	row := q.db.QueryRowContext(ctx, createParam,
		arg.UserID,
		arg.ParamTypeID,
		arg.Value,
		arg.Timestamp,
	)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParamTypeID,
		&i.Value,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getParam = `-- name: GetParam :one
SELECT id, user_id, param_type_id, value, timestamp, created_at FROM params
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetParam(ctx context.Context, id int64) (Param, error) {
	row := q.db.QueryRowContext(ctx, getParam, id)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParamTypeID,
		&i.Value,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getParamsByType = `-- name: GetParamsByType :many
SELECT p.id, p.value, p.timestamp, p.created_at 
FROM params as p
INNER JOIN param_types as t ON p.param_type_id = t.id
WHERE p.user_id = $1
	AND t.name = $2
	AND p.timestamp >= $3
	AND p.timestamp < $4
ORDER BY p.timestamp
LIMIT $6
OFFSET $5
`

type GetParamsByTypeParams struct {
	UserID        int64     `json:"user_id"`
	ParamTypeName string    `json:"param_type_name"`
	From          time.Time `json:"from"`
	To            time.Time `json:"to"`
	Offset        int32     `json:"offset"`
	Limit         int32     `json:"limit"`
}

type GetParamsByTypeRow struct {
	ID        int64     `json:"id"`
	Value     float64   `json:"value"`
	Timestamp time.Time `json:"timestamp"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetParamsByType(ctx context.Context, arg GetParamsByTypeParams) ([]GetParamsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getParamsByType,
		arg.UserID,
		arg.ParamTypeName,
		arg.From,
		arg.To,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetParamsByTypeRow{}
	for rows.Next() {
		var i GetParamsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
