// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: param_origin.sql

package db

import (
	"context"
)

const listParamOrigins = `-- name: ListParamOrigins :many
SELECT id, param_type_name, name, created_by, created_at 
FROM param_origins
WHERE param_type_name = $1
`

func (q *Queries) ListParamOrigins(ctx context.Context, paramTypeName string) ([]ParamOrigin, error) {
	rows, err := q.db.QueryContext(ctx, listParamOrigins, paramTypeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParamOrigin{}
	for rows.Next() {
		var i ParamOrigin
		if err := rows.Scan(
			&i.ID,
			&i.ParamTypeName,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
