// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, username string) (User, error)
	CreateValue(ctx context.Context, arg CreateValueParams) (Value, error)
	CreateValueType(ctx context.Context, arg CreateValueTypeParams) (ValueType, error)
	DeleteUser(ctx context.Context, id int64) error
	GetByUsername(ctx context.Context, username string) (User, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetValue(ctx context.Context, id int64) (Value, error)
	GetValueType(ctx context.Context, id int64) (ValueType, error)
	GetValueTypeByName(ctx context.Context, arg GetValueTypeByNameParams) (ValueType, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListValuesPerType(ctx context.Context, arg ListValuesPerTypeParams) ([]Value, error)
}

var _ Querier = (*Queries)(nil)
