// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateParam(ctx context.Context, arg CreateParamParams) (Param, error)
	CreateParamType(ctx context.Context, arg CreateParamTypeParams) (ParamType, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetParam(ctx context.Context, id int64) (Param, error)
	GetParamType(ctx context.Context, id int64) (ParamType, error)
	GetParamTypeByName(ctx context.Context, arg GetParamTypeByNameParams) (ParamType, error)
	GetParamsByType(ctx context.Context, arg GetParamsByTypeParams) ([]GetParamsByTypeRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
