name: Deploy to production

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout branch
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - id: secrets
        name: Get Secret Manager secrets
        uses: google-github-actions/get-secretmanager-secrets@v0
        with:
          secrets: |-
            db:projects/585499903514/secrets/aqualog-db-production

      - name: Dump env
        env:
          DB_SOURCE: "${{ steps.secrets.outputs.db }}"
        run: |
          pip install dump-env
          dump-env --source=app.env > app.env
          cat app.env
